#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(set = 0, binding = 0, rgba32f) uniform readonly image2D inputImage;
layout(set = 0, binding = 1, rgba8) uniform writeonly image2D outputImage;

layout(local_size_x = 16, local_size_y = 16) in;

void main()
{
  ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
  vec4 hdrColor = imageLoad(inputImage, pixel);
  imageStore(outputImage, pixel, clamp(hdrColor, 0.0, 1.0));
}
