#version 430
#extension GL_GOOGLE_include_directive : require

#include "UniformParams.h"

layout(local_size_x = 32, local_size_y = 32) in;

layout(binding = 7) uniform Params {
    UniformParams params;
};

layout(binding = 8, rgba8) uniform image2D img;

#define INF 1e5
#define POINTS 8
#define PI      3.141592
#define TWO_PI  6.2831852

const vec3 kUp = vec3(0.0, 2.0, 0.0);
const float kEps = 0.01;

const float PalmTrunkLength = 1.5;
const float PalmTrunkRadius = 0.02;
const float PalmTrunkSkew = 1.8;
const float TrunkPower = 2.0;
const float TrunkPowerFactor = 0.03;

float noise(vec3 pos, float speed)
{
    float time = params.iTime * 2.0 * speed;
    return (
        sin(pos.x * 1.7 + pos.z * 0.3 + time) * 0.3 +
        cos(pos.x * 1.3 + pos.z * 0.5 + time * 0.7) * 0.2 +
        cos(pos.x * 0.4 + pos.z * 1.5 - time * 0.3) * 0.4 +
        cos(-pos.x * 0.4 + pos.z * 1.5 + time * 1.2) * 0.3
    ) / 2.0 + 0.5;
}

vec2 rotate(vec2 p, float angle) {
    float c = cos(angle);
    float s = sin(angle);
    return vec2(c * p.x - s * p.y, s * p.x + c * p.y);
}

// Rotation matrix around the X axis.
mat3 rotateX(float theta) {
    float c = cos(theta);
    float s = sin(theta);
    return mat3(
        vec3(1, 0, 0),
        vec3(0, c, -s),
        vec3(0, s, c)
    );
}

// Rotation matrix around the Y axis.
mat3 rotateY(float theta) {
    float c = cos(theta);
    float s = sin(theta);
    return mat3(
        vec3(c, 0, s),
        vec3(0, 1, 0),
        vec3(-s, 0, c)
    );
}

// Rotation matrix around the Z axis.
mat3 rotateZ(float theta) {
    float c = cos(theta);
    float s = sin(theta);
    return mat3(
        vec3(c, -s, 0),
        vec3(s,  c, 0),
        vec3(0,  0, 1)
    );
}


vec2 hash21(float n) {
    return fract(sin(vec2(n, n+1.23)) * vec2(43758.5453, 22578.1459));
}

vec3 rgba(int red, int green, int blue, int alpha)
{
    return vec3(float(red) / 256.0, float(green) / 256.0, float(blue) / 256.0);
}

float island(vec3 pos)
{

    float sphere = length(pos + vec3(0.0,0.4,0.0)) - 0.5;

    return max(sphere, -pos.y);
}

float sdTrunk(vec3 pos)
{

    vec3 p = pos - vec3(0.0, 0.1, 0.0); // центр ствола на острове

    // наклон ствола по высоте
    float f = clamp(p.y / PalmTrunkLength, 0.0, 1.0);
    p.xy = rotate(p.xy, -p.y * p.y * PalmTrunkSkew);


    float d = length(p.xz) - (PalmTrunkRadius - pow(f, TrunkPower) * TrunkPowerFactor * 10.0);


    d = max(d, -p.y); 
    d = max(d, p.y - PalmTrunkLength); 

    return d;
}




float water(vec3 pos)
{
    float tinyRipples = noise(pos * 50.0, 1.0) * 0.01;
    return pos.y - tinyRipples;
}



float sdCutHollowSphere(vec3 p, float r, float h, float t, vec3 n)
{

    n = normalize(n);

    // проекция точки на нормаль
    float axis = dot(p, n);


    float radial = length(p - n * axis);

    float w = sqrt(r*r - h*h);
    vec2 q = vec2(radial, axis);

    return ((h*q.x < w*q.y) ? length(q - vec2(w,h)) : abs(length(q) - r)) - t;
}


float globalSdf(int object, vec3 pos)
{
    if (object == 1)
        return water(pos);
    else {
        float islandSDF = island(pos);
        float trunkSDF = sdTrunk(pos);


        float leafSDF = INF;
        for (int i = 0; i < POINTS; i++)
        {
            float angle = float(i) * TWO_PI / float(POINTS);
            vec3 leafPos = pos - vec3(-0.064, PalmTrunkLength-1.083, 0.0);
            float lSDF = sdCutHollowSphere(leafPos, 0.1, 0.0, 0.01, vec3(1,-1,0));
            leafSDF = min(leafSDF, lSDF);
        }

        return min(min(islandSDF, trunkSDF), leafSDF);
    }
}

float trace(int object, vec3 start, vec3 ray, out vec3 position, out vec3 normal)
{
    int iterations = 99;
    
    vec3 pos = start;

    if (object == 1 && ray.y < 0.0)
    {
        pos -= ray * (pos.y / ray.y);
    }
    
    float sdf = 0.0;
    for (int iter = 0; iter < iterations; ++iter)
    {
        sdf = globalSdf(object, pos);
        pos += normalize(ray) * sdf;

        if (object == 0 && abs(pos.z) > 1.0)
            break;

        if (object == 1 && ray.y >= 0.0)
            break;
    }

    position = pos;
    normal.x = globalSdf(object, pos + vec3(kEps, 0.0, 0.0)) - sdf;
    normal.y = globalSdf(object, pos + vec3(0.0, kEps, 0.0)) - sdf;
    normal.z = globalSdf(object, pos + vec3(0.0, 0.0, kEps)) - sdf;
    normal = normalize(normal);

    return sdf;
}



vec3 deepBlue(vec3 ray)
{
    vec3 zenith = rgba(113, 164, 219, 1);
    vec3 horizon = rgba(25, 51, 117, 1);
    float interpolation = pow(normalize(ray).y + 1.0, 4.0);

    vec3 color = zenith * interpolation + horizon * (1.0 - interpolation);

    return color;
}

vec3 sky(vec3 ray)
{
    vec3 zenith = rgba(116, 92, 97, 1);
    vec3 horizon = rgba(179, 124, 100, 1);
    float interpolation = smoothstep(0.0, 1.0, normalize(ray).y / 2.0 + 0.5);

    vec3 color = zenith * interpolation + horizon * (1.0 - interpolation);

    return color;
}

vec3 islandColor(vec3 normal) {
    return rgba(237, 201, 175, 1); 
}

vec3 trunkColor(vec3 pos) {
	pos.y *= 1.2;
	vec3 brown = vec3(0.48, 0.29, 0.070) * 0.7;

	float ang = atan(pos.z, pos.x) * 14.0 + pos.y * 12.0;
	float y = pos.y + cos(ang) * 0.02;

	float x = cos(y * 14.0);
	x *= x;
	x *= x;

	return mix(brown, brown * 0.6, x);
}

vec3 kSun = normalize(vec3(-0.2, -1.0, 0.2));

float specular(vec3 normal, vec3 view)
{

    vec3 bisector = normalize(-view - kSun);
    return pow(max(0.0, dot(bisector, normal)), 170.0);
}

vec3 shade(vec3 normal, vec3 view)
{
    vec3 albedo = islandColor(normal);
    vec3 ao = albedo * (sky(normal) + vec3(1.0)) / 2.0;
    vec3 direct = albedo * dot(normal, -kSun);
    vec3 spec = vec3(1.0) * specular(normal, view);
    return direct * 0.3 + ao * 0.9  + spec * 0.2;
}

vec3 leafColor(vec3 pos)
{

    float n = noise(pos * 5.0, 1.0);
    return mix(vec3(0.1,0.6,0.2), vec3(0.05,0.4,0.1), n);
}


vec3 shadeIsland(vec3 pos, vec3 normal)
{

    bool isTrunk = sdTrunk(pos) < 0.01;


    float leafSDF = INF;
    bool isLeaf = leafSDF < 1.01;
    

    vec3 albedo = isLeaf ? leafColor(pos) : (isTrunk ? trunkColor(pos) : islandColor(normal));


    vec3 sunDir = normalize(vec3(-0.6, 0.3, 0.2));
    vec3 sunColor = rgba(189, 188, 14, 1);

    float diffuse = max(0.0, dot(normal, sunDir));
    float ambient = 0.3;
    float light = diffuse * 0.8 + ambient;

    return albedo * (sunColor * light);
}

vec3 colorCorrect(vec3 color)
{
    vec3 result = color;
    result.x = smoothstep(0.0, 1.0, color.x);
    result.y = smoothstep(0.0, 1.0, color.y);
    result.z = smoothstep(0.0, 1.0, color.z);
    return result;
}

vec3 shadeWater(vec3 pos, vec3 normal, vec3 view)
{
    vec3 refracted = refract(view, normal, 1.0 / 1.33);
    vec3 reflected = reflect(view, normal);

    vec3 reflectedSky = sky(reflected);
    
    vec3 islandPosition;
    vec3 islandNormal;
    float dist = trace(0, pos, refracted, islandPosition, islandNormal);


    vec3 result = mix(deepBlue(refracted), rgba(115, 224, 238, 1), pos.y / 0.6);
    result = mix(result, reflectedSky, pow(1.0 - abs(view.y), 3.0) * 0.75);
    if (dist < kEps)
    {
        result = shade(islandNormal, refracted);
        vec3 mixedWaterColor = deepBlue(islandNormal);
        mixedWaterColor = mix(mixedWaterColor, rgba(55, 99, 180, 1), 0.4);
        result = mix(result, mixedWaterColor, 0.6);
    }

    if (island(pos) < noise(pos * 100.0, 3.0) * 0.01 + 0.005)
    {
        result = rgba(216, 240, 243, 1);
    }

   

    result += specular(normal, view) * vec3(1.0) * 0.04;

    return result;
}

void main()
{
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);
    
    if (fragCoord.x >= params.iResolution.x || fragCoord.y >= params.iResolution.y) {
        return;
    }
    
    vec2 uv = vec2(fragCoord) / params.iResolution.xy;
    uv.y = 1.0 - uv.y; 
    
    
    vec2 mouse = params.iMouse.xy / params.iResolution.xy - vec2(0.5);

    vec3 cameraPos = normalize(vec3(mouse.x, mouse.y + 0.9, 1.5)) * 0.9;
    vec3 forward = normalize(vec3(0.0, 0.2, 0.0) - cameraPos);
    vec3 right = normalize(cross(forward, kUp));
    vec3 up = normalize(cross(right, forward));
    
    vec2 relativeScreen = (uv - 0.5) * params.iResolution.xy / params.iResolution.x * 2.0;
    
    vec3 ray = forward + relativeScreen.x * right + relativeScreen.y * up;
    
    vec3 islandPosition;
    vec3 islandNormal;
    float islandDelta = trace(0, cameraPos, ray, islandPosition, islandNormal);
    
    vec3 waterPosition;
    vec3 waterNormal;
    float waterDelta = trace(1, cameraPos, ray, waterPosition, waterNormal);
    
    vec3 col = sky(ray);
    
    if ((distance(islandPosition, cameraPos) < distance(waterPosition, cameraPos) || waterDelta > kEps) &&
        islandDelta < kEps) {
        col = shadeIsland(islandPosition, islandNormal);
    }
    else if (waterDelta < kEps) {
        col = shadeWater(waterPosition, waterNormal, normalize(waterPosition - cameraPos));
    }
    col = colorCorrect(col);
    
    imageStore(img, fragCoord, vec4(col, 1.0));
}